- defaults:
    name: global
    description: |
      This job is managed by puppet and will be overwritten.
    project-type: freestyle
    concurrent: true

    wrappers:
      - timeout:
          timeout: 30
          fail: true
      - timestamps

    logrotate:
      daysToKeep: 1
      numToKeep: -1
      artifactDaysToKeep: -1
      artifactNumToKeep: -1
