- job:
    name: download-and-test
    display-name: 'Download and unit test'
    builders:
      - shell: |
          export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
          bundle install --path ../cache/vendor
          bundle exec rake db:setup
          bundle exec rake test

    scm:
      - git:
          url: https://github.com/OWASP/railsgoat.git
          branches:
            - master

    properties:
      - batch-tasks:
          - name: Clear bundler cache
            script: rm -fr ../cache/vendor

    publishers:
      - clone-workspace

- job:
    name: static-analysis
    display-name: 'Brakeman static analysis scan'
    builders:
      - shell: "brakeman -o brakeman-output.tabs --no-progress --separate-models"

    scm:
      - workspace:
          parent-job: download-and-test

    publishers:
      - brakeman:
          output: brakeman-output.tabs

- job:
    name: virus-scan
    display-name: 'Virus scanning'

    scm:
      - workspace:
          parent-job: download-and-test

    publishers:
      - clamav:
          includes: "**"


- job:
    name: bundler-audit
    display-name: 'Check known vulnerabilities in dependencies'
    builders:
      - shell: bundle-audit

    scm:
      - workspace:
          parent-job: download-and-test

- job:
    name: zapr
    display-name: 'Scan with OWASP ZAP'

    builders:
      - shell: |
          #/bin/bash
          export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
          bundle install --path ../cache/vendor
          bundle exec rake db:setup
          bundle exec rails server -d
          zapr --summary --debug --zap-path /opt/zap/zap.sh http://localhost:3000/
          kill $(ps aux | grep '[r]ails server' | awk '{print $2}')

    scm:
      - workspace:
          parent-job: download-and-test

- job:
    name: start
    project-type: flow
    block-downstream: true
    dsl: |
      build("download-and-test")
      parallel (
        { build("static-analysis") },
        { build("virus-scan") },
        { ignore(FAILURE) {
            build("bundler-audit")
        }}
      )
      build("zapr")

