- job:
    name: download-and-test
    display-name: 'Download and unit test'
    builders:
      - shell: |
          export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
          bundle install --path ../cache/vendor
          bundle exec rake db:setup
          bundle exec rake test

    scm:
      - git:
          url: https://github.com/OWASP/railsgoat.git
          branches:
            - master

    properties:
      - batch-tasks:
          - name: Clear bundler cache
            script: rm -fr ../cache/vendor

    publishers:
      - clone-workspace

- job:
    name: integration-test
    display-name: 'Run integration tests'

    builders:
      - shell: |
          export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
          gemrat ci_reporter
          bundle install --path ../cache/vendor
          bundle exec rake db:setup
          bundle exec rake -f /var/lib/jenkins/jobs/download-and-test/cache/vendor/ruby/2.0.0/gems/ci_reporter-1.9.2/stub.rake ci:setup:rspecdoc spec

    scm:
      - workspace:
          parent-job: download-and-test

    publishers:
      - blame-upstream
      - junit:
          results: spec/reports/*.xml
          test-stability: true

- job:
    name: code-metrics
    display-name: 'Code metrics'
    builders:
      - shell: "sloccount --duplicates --wide --details . > sloccount.sc"

    scm:
      - workspace:
          parent-job: download-and-test

    publishers:
      - sloccount:
          report-files: sloccount.sc
          charset: UTF-8
      - blame-upstream

- job:
    name: static-analysis
    display-name: 'Static analysis'
    builders:
      - shell: "brakeman -o brakeman-output.tabs --no-progress --separate-models"

    scm:
      - workspace:
          parent-job: download-and-test

    publishers:
      - brakeman:
          output: brakeman-output.tabs
- job:
    name: virus-scan
    display-name: 'Virus scanning'

    scm:
      - workspace:
          parent-job: download-and-test

    publishers:
      - clamav:
          includes: "**"
      - blame-upstream

- job:
    name: bundler-audit
    display-name: 'Check known vulnerabilities in dependencies'

    builders:
      - shell: bundle-audit

    scm:
      - workspace:
          parent-job: download-and-test

    publishers:
      - blame-upstream

- job:
    name: zapr
    display-name: 'Active vulnerability scan'

    builders:
      - shell: |
          #/bin/bash
          export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
          bundle install --path ../cache/vendor
          bundle exec rake db:setup
          bundle exec rails server -d
          zapr --summary --debug --zap-path /opt/zap/zap.sh http://localhost:3000/
          kill $(ps aux | grep '[r]ails server' | awk '{print $2}')

    scm:
      - workspace:
          parent-job: download-and-test

    publishers:
      - blame-upstream

- job:
    name: start
    project-type: flow
    block-downstream: true
    dsl: |
      build("download-and-test")
      parallel (
        { build("zapr") },
        { build("static-analysis") },
        { build("code-metrics") },
        { build("virus-scan") },
        { ignore(FAILURE) {
            build("bundler-audit")
        }}
      )
      ignore(FAILURE) {
        build("integration-test")
      }
    publishers:
      - aggregate-tests

